export const LicenseConstants = {
    CUSTOMER: 'customer',
    OFFICER: 'officer',

    LOCALITY_URBAN: 'URBAN',
    LOCALITY_RURAL: 'RURAL',

    STR_CUSTOMER: 'customer',
    STR_LEVEL_ONE: 'Level 1',
    STR_MODULE_NAME: 'licence-mangement',
    STR_LICENCE_FEE: 'License Fees',
    STR_PROCESSING_FEE: 'Processing Fees',

    MSG_NO_RESP: 'Response content not available',
    MSG_NO_PAYMENT_METHOD: 'Payment method not selected',
    MSG_NO_APPLICATION_NUMBER: 'Error while getting application number',

    STATUS_DRAFT: 'DRAFT',
    STATUS_SAVE: 'SAVE',
    STATUS_SUBMITTED: 'SUBMITTED',
    STATUS_APPROVED: 'APPROVED',
    STATUS_REJECTED: 'REJECTED',
    STATUS_SENDBACK: 'SENDBACK',
    STATUS_IN_PROGRESS: 'IN_PROGRESS',
    STATUS_PENDING_LICENSE_FEE: 'PENDING_LICENSE_FEE',
    STATUS_PENDING_DSC: 'PENDING_DSC',
    STATUS_PENDING_SITE_INFO: 'PENDING_SITE_INFO',
    STATUS_PENDING_SITE_VISIT: 'PENDING_SITE_VISIT', 
    STATUS_APPROVED_SITE_VISIT: 'APPROVED_SITE_VISIT',
    STATUS_SENDBACK_SITE_INFO: 'SENDBACK_SITE_INFO', 
    STATUS_REJECTED_SITE_VISIT: 'REJECTED_SITE_VISIT', 
    STATUS_FORWARD_REJECTED_SITE_VISIT: 'FORWARD_REJECTED_SITE_VISIT',
    STATUS_SEND_BACK_REJECTED_SITE_VISIT: 'SEND_BACK_REJECTED_SITE_VISIT',
    STATUS_RECONSIDER_REJECTED_SITE_VISIT: 'RECONSIDER_REJECTED_SITE_VISIT',

    EVENT_INITIATE: 'INITIATE',
    EVENT_SITE_VISIT_OFFICER_ASSIGMENT: 'SITE_VISIT_OFFICER_ASSIGMENT',
    EVENT_SENDBACK_SITE_INFO: 'SENDBACK_SITE_INFO',
    EVENT_PENDING_SITE_INFO: 'PENDING_SITE_INFO',
    EVENT_PENDING_DSC: 'PENDING_DSC',
    EVENT_LICENSE_RELEASE: 'LICENSE_RELEASE',

    CODE_SALUTATION: 'SALUTATION',
    CODE_GENDER: 'GENDER',
    CODE_ENTITYOFFIRM: 'ENTITYOFFIRM',
    CODE_ENTITY_FOR_AUTH_PERSON: 'ENTITY_FOR_AUTH_PERSON',
    CODE_LOCALITYTYPE: 'LOCALITYTYPE',
    CODE_BANK: 'BANK',
    CODE_ITR: 'ITR',
    CODE_YEAR_OF_REGISTRATION: 'CODE_YEAR_OF_REGISTRATION',
    CODE_BOTTLING_UNIT: 'BOTTLING_UNIT',
    CODE_OWNERSHIP_TYPE: 'OWNERSHIP_TYPE',
    CODE_PAYMENT_TYPE: 'PAYMENT_TYPE',
    CODE_NUMBER_OF_ROOMS: 'NUMBER_OF_ROOMS',
    CODE_DISTRICT_CATEGORY: 'DISTRICT_CATEGORY',
    CODE_RETAIL_SHOP: 'RETAIL_SHOP',
    CODE_EVENT_TYPE: 'EVENT_TYPE',
    CODE_EVENT_HOLDER: 'EVENT_HOLDER',
    CODE_CHECKLIST_EVENT_BAR_FL11: 'CHECKLIST_EVENT_BAR_FL11', 
    CODE_CHECKLIST_BWFL_PARENT_UNIT: 'CHECKLIST_BWFL_PARENT_UNIT',
    CODE_STATE_POPULATION_SUPPLY: 'STATE_POPULATION_SUPPLY',

    CODE_CHECKLIST_WHOLESALE_FL2: 'CHECKLIST_WHOLESALE_FL2',
    CODE_CHECKLIST_WHOLESALE_FL2A: 'CHECKLIST_WHOLESALE_FL2A',
    CODE_CHECKLIST_WHOLESALE_FL2B: 'CHECKLIST_WHOLESALE_FL2B',
    CODE_CHECKLIST_WHOLESALE_CL2: 'CHECKLIST_WHOLESALE_CL2',
    CODE_CHECKLIST_WHOLESALE_ID3: 'CHECKLIST_WHOLESALE_ID3',

    CODE_CHECKLIST_BOND_WAREHOUSE_2A: 'CHECKLIST_BOND_WAREHOUSE_2A',
    CODE_CHECKLIST_BOND_WAREHOUSE_2B: 'CHECKLIST_BOND_WAREHOUSE_2B',
    CODE_CHECKLIST_BOND_WAREHOUSE_2C: 'CHECKLIST_BOND_WAREHOUSE_2C',
    CODE_CHECKLIST_BOND_WAREHOUSE_2D: 'CHECKLIST_BOND_WAREHOUSE_2D',

    // For DISTILLERY
    CODE_CHECKLIST_DISTI_BOTTL_CL_B1: 'CODE_CHECKLIST_DISTI_BOTTL_CL_B1',
    CODE_CHECKLIST_DISTI_BOTTL_CL_B2: 'CODE_CHECKLIST_DISTI_BOTTL_CL_B2',
    CODE_CHECKLIST_DISTI_BOTTL_DS_1: 'CODE_CHECKLIST_DISTI_BOTTL_DS_1',
    CODE_CHECKLIST_DISTI_BOTTL_FL_1: 'CODE_CHECKLIST_DISTI_BOTTL_FL_1',
    CODE_CHECKLIST_DISTI_BOTTL_FL_1A: 'CODE_CHECKLIST_DISTI_BOTTL_FL_1A',
    CODE_CHECKLIST_DISTI_BOTTL_FL_3: 'CODE_CHECKLIST_DISTI_BOTTL_FL_3',
    CODE_CHECKLIST_DISTI_BOTTL_FL_3A: 'CODE_CHECKLIST_DISTI_BOTTL_FL_3A',
    CODE_CHECKLIST_DISTI_BOTTL_FL_16: 'CODE_CHECKLIST_DISTI_BOTTL_FL_16',
    CODE_CHECKLIST_DISTI_BOTTL_FL_17: 'CODE_CHECKLIST_DISTI_BOTTL_FL_17',
    CODE_CHECKLIST_DISTI_BOTTL_FL_32: 'CODE_CHECKLIST_DISTI_BOTTL_FL_32',
    CODE_CHECKLIST_DISTI_BOTTL_FL_39: 'CODE_CHECKLIST_DISTI_BOTTL_FL_39',
    CODE_CHECKLIST_DISTI_BOTTL_FL_40: 'CODE_CHECKLIST_DISTI_BOTTL_FL_40',
    CODE_CHECKLIST_DISTI_BOTTL_FL_41: 'CODE_CHECKLIST_DISTI_BOTTL_FL_41',
    CODE_CHECKLIST_DISTI_BOTTL_FL_49: 'CODE_CHECKLIST_DISTI_BOTTL_FL_49',
    CODE_CHECKLIST_DISTI_BOTTL_PD_1: 'CODE_CHECKLIST_DISTI_BOTTL_PD_1',
    CODE_CHECKLIST_DISTI_BOTTL_PD_2: 'CODE_CHECKLIST_DISTI_BOTTL_PD_2',
    CODE_CHECKLIST_DISTI_BOTTL_PD_32: 'CODE_CHECKLIST_DISTI_BOTTL_PD_32',
    CODE_CHECKLIST_DISTI_BOTTL_PD_33: 'CODE_CHECKLIST_DISTI_BOTTL_PD_33',
    CODE_CHECKLIST_DISTI_BOTTL_PD_34: 'CODE_CHECKLIST_DISTI_BOTTL_PD_34',

    FF_APPLI: 'ApplicantFiles', // FileFor Applicant
    FF_ADDRESS: 'AddressFiles', // FileFor Address section
    FF_ATTACHMENTS: 'Attachments', // FileFor Attachments
    FF_BANK: 'BankFiles', // FileFor BankDet
    FF_BUSS_UNIT: 'BussinessFiles', // FileFor BussinessFiles
    FF_FIRM_COMPANY: 'FirmCompanyFiles', // FileFor FirmCompanyFiles
    FF_PREMISES: 'PremisesFiles', // FileFor PremisesFiles
    FF_SITE_DOCUMENT: 'SiteDocumentFiles', // FileFor SiteDocumentFiles

    SEC_ADDR_APPLICANT: 'applicant_address',
    SEC_ADDR_PREMISES: 'premises_address',
    SEC_ADDR_VENUE: 'venue_address',
    SEC_ADDR_UNIT: 'unit_address',
    SEC_ADDR_BWFL_PREMISES: 'bwfl_parent_premises_address',
    SEC_ADDR_BWFL_PARENT_UNIT: 'bwfl_parent_unit_address',

    PROP_APPLI_DET: 'applicantDetails',
    PROP_ADDRESS_DET: 'addressList',
    PROP_BANK_DET: 'bankList',
    PROP_BUSSIN_UNIT: 'businessUnitDetails',
    PROP_AUTH_PERSON_ADDRESS_DET: 'authorizePersonAddressList',

    PROP_LICENSE_WL: 'wholeSaleLicenses',
    PROP_ATTACHMENT_WL: 'wholeSaleAdditionalDetails',
    PROP_SCHEDULE_WL: 'scheduleList',

    PROP_LICENSE_HBR: 'hbrLicenses',
    PROP_FIRM_COMPANY_DET_HBR: 'hbrFirmCompanyDetailList',
    PROP_ATTACHMENT_HBR: 'hbrAdditionalDetails',
    PROP_PREMISES_HBR: 'hbrPremisesDetails',

    PROP_SITE_DOCUMENT: 'documentList',

    PROP_LICENSE_EVENT_BAR: 'eventBarLicenses',
    PROP_PRODUCT_LIST: 'productList',

    PROP_LICENSE_DL: 'distilleryLicenses',
    PROP_ATTACHMENT_DL: 'distilleryAdditionalDetails',

    COMMENT_ACTION_CLARIFICATION: 'SENDBACK',
    COMMENT_ACTION_REJECTED: 'REJECTED',
    COMMENT_ACTION_SAVE: 'SAVE',
    COMMENT_SENDBACK_SITE_INFO: 'SENDBACK_SITE_INFO',
    COMMENT_SENDBACK: 'SENDBACK',
    /**
     * Fee type for processing and license maintain as constant
     */
    FEE_TYPE_APPLICATION_PROCESSING: 'PROCESSING_FEE',
    FEE_TYPE_LICENSE_PROCESSING: 'LICENSE_FEE',

    // Applicant Document identifiers for all licenses
    FN_APPLI_PHOTO: 'Photo of Applicant',
    FN_APPLI_AADHAR: 'Applicant Aadhar',
    FN_APPLI_PAN: 'Applicant Pan',
    FN_APPLI_ITR: 'Applicant ITR',

    SRC_APPLI_PHOTO: 'appli_photo_file_source',
    SRC_APPLI_AADHAR: 'appli_aadhar_file_source',
    SRC_APPLI_PAN: 'appli_pan_file_source',
    SRC_APPLI_ITR: 'appli_itr_file_source',

    // Address Document identifiers for all licenses
    FN_ADDR_BOUNDRY: 'Upload Boundries',
    SRC_ADDR_BOUNDRY: 'boundries_file_source',

    FN_ADDR_OWNERSHIIP_DOC: 'Ownership Document',
    SRC_ADDR_OWNERSHIIP_DOC: 'ownershipDoc_file_source',

    // Bank Document identifiers for all licenses
    FN_BK_CAN_CHEQUE: 'Cancel Cheque',
    SRC_BK_CAN_CHEQUE: 'cancel_cheque_file_source',

    // Attachment Document identifiers for all licenses
    FN_ATTACH_SOLVENCYCERT: 'Solvency Certificate',
    FN_ATTACH_AFFADAVAIT: 'Affadavait',
    FN_ATTACH_BOUNDRY: 'Upload Boundries',
    FN_ATTACH_LAY_PLAN: 'Layout plan',
    FN_ATTACH_CERT_OF_INCORP: 'Certification of Incorporation',
    FN_ATTACH_MOM_OF_ASSO: 'Memorandum of Association',
    FN_ATTACH_ART_OF_ASSOC: 'Article of Association',
    FN_ATTACH_RESU_OF_AUTH: 'Resolution of Authorization',
    FN_ATTACH_TAN: 'TAN',
    FN_ATTACH_CERT_OF_FIRM: 'Registration Certificate of firm',
    FN_ATTACH_PARTNERSHIPDEED: 'Partnership deed',
    FN_ATTACH_LISTOFDIRECTORS: 'List of directors/partner',
    FN_ATTACH_TRADELICENCE: 'Copy of Trade Licence',
    FN_ATTACH_FIRESAFTEYNOC: 'Fire saftey NoC',
    FN_ATTACH_FSSAI_CERT: 'Fssai Certificate',
    FN_ATTACH_CERT_OF_PREMISESUTILITY: 'Certification of premises utility',
    FN_ATTACH_LAWANDORDER: 'Law & Order ',
    FN_ATTACH_LISTOFPRESIDENT: 'List of President and office Bearers',
    FN_ATTACH_RULESOFMEMBERSHIP: 'Copy of Rules of membership',
    FN_ATTACH_PROOFOFPARKINGPLACE: 'Proof Of Parking',
    FN_ATTACH_GSTIN: 'GSTIN File',
    FN_ATTACH_NOC_OF_PREMISES: 'NoC of Premises',
    FN_ATTACH_CERT_OF_POLLUT_CNTRL: 'Certificate of pollution control',

    SRC_ATTACH_SOLVENCYCERT: 'solvencyCertByAuth_file_source',
    SRC_ATTACH_AFFADAVAIT: 'affadavait_file_source',
    SRC_ATTACH_BOUNDRY: 'boundries_file_source',
    SRC_ATTACH_LAY_PLAN: 'layoutPlan_file_source',
    SRC_ATTACH_CERT_OF_INCORP: 'certificationOfIncorporation_file_source',
    SRC_ATTACH_MOM_OF_ASSO: 'memorandumOfAssociation_file_source',
    SRC_ATTACH_ART_OF_ASSOC: 'articleOfAssociation_file_source',
    SRC_ATTACH_RESU_OF_AUTH: 'resolutionOfAuthorization_file_source',
    SRC_ATTACH_TAN: 'TAN_file_source',
    SRC_ATTACH_CERT_OF_FIRM: 'certificateOfFirm_file_source',
    SRC_ATTACH_PARTNERSHIPDEED: 'partnershipDeed_file_source',
    SRC_ATTACH_LISTOFDIRECTORS: 'listOfDirectors_file_source',
    SRC_ATTACH_TRADELICENCE: 'tradeLicence_file_source',
    SRC_ATTACH_FIRESAFTEYNOC: 'fireSafteyNoc_file_source',
    SRC_ATTACH_FSSAI_CERT: 'fssaiCertificate_file_source',
    SRC_ATTACH_CERT_OF_PREMISESUTILITY: 'certificationOfPremisesUtility_file_source',
    SRC_ATTACH_LAWANDORDER: 'lawAndOrder_file_source',
    SRC_ATTACH_LISTOFPRESIDENT: 'listOfPresident_file_source',
    SRC_ATTACH_RULESOFMEMBERSHIP: 'rulesOfMembership_file_source',
    SRC_ATTACH_PROOFOFPARKINGPLACE: 'proofOfParkingPlace_file_source',
    SRC_ATTACH_GSTIN: 'uploadGstin_file_source',
    SRC_ATTACH_NOC_OF_PREMISES: 'nocOfPremises_file_source',
    SRC_ATTACH_CERT_OF_POLLUT_CNTRL: 'certOfPollutionControl_file_source',

    // Bussiness Unit Document identifiers for all licenses
    FN_BUSSUNIT_COMP_PAN: 'Upload Company/Firm PAN Number',
    FN_BUSSUNIT_ITR_LASTYR: 'Last Year ITR',
    FN_BUSSUNIT_CERT_INCORP: 'Certificate Incorporation',
    FN_BUSSUNIT_MOM_OF_ARTICLE: 'Memorandum of Article',
    FN_BUSSUNIT_ART_OF_ASSOC: 'Article of Association',
    FN_BUSSUNIT_RESU_OF_AUTH: 'Resolution of Authorization',
    FN_BUSSUNIT_OWNERSHIIP_DOC: 'Ownership Document',
    FN_BUSSUNIT_UNIT_LICENSE: 'Unit License',
    FN_BUSSUNIT_AFFADAVAIT: 'Unit Affadavait',
    FN_BUSSUNIT_GSTIN: 'GSTIN File',
    FN_BUSSUNIT_ANNUAL_TURNOVER_CERT: 'Certificate of Annual Turnover',
    FN_BUSSUNIT_CERT_OF_OTHER_STATE_OFFICIAL: 'Certificate of Other State Excise Official',
    FN_BUSSUNIT_DECLARATION: 'Unit Declaration',
    FN_BUSSUNIT_BOND_DOC: 'BWFL 3 Bond Document',
    FN_BUSSUNIT_POWER_OF_ATTORNEY: 'Power of Attorney',

    SRC_BUSSUNIT_COMP_PAN: 'compFirmPan_file_source',
    SRC_BUSSUNIT_ITR_LASTYR: 'lastYrITR_file_source',
    SRC_BUSSUNIT_CERT_INCORP: 'certIncorp_file_source',
    SRC_BUSSUNIT_MOM_OF_ARTICLE: 'memoOfArti_file_source',
    SRC_BUSSUNIT_ART_OF_ASSOC: 'artiOfAssoc_file_source',
    SRC_BUSSUNIT_RESU_OF_AUTH: 'resoluOfAuth_file_source',
    SRC_BUSSUNIT_OWNERSHIIP_DOC: 'ownershipDoc_file_source',
    SRC_BUSSUNIT_UNIT_LICENSE: 'unitLicense_file_source',
    SRC_BUSSUNIT_AFFADAVAIT: 'unitAffadavait_file_source',
    SRC_BUSSUNIT_GSTIN: 'uploadGstin_file_source',
    SRC_BUSSUNIT_ANNUAL_TURNOVER_CERT: 'annualTurnOverCert_file_source',
    SRC_BUSSUNIT_CERT_OF_OTHER_STATE_OFFICIAL: 'stateExciseOfficialCert_file_source',
    SRC_BUSSUNIT_DECLARATION: 'declarationCert_file_source',
    SRC_BUSSUNIT_BOND_DOC: 'bwflBondDoc_file_source',
    SRC_BUSSUNIT_POWER_OF_ATTORNEY: 'powerOfAttorney_file_source',

    // Premises Document identifiers for HBR license
    FN_HBR_PREM_OWNERSHIIP_DOC: 'Ownership Document',
    SRC_HBR_PREM_OWNERSHIIP_DOC: 'ownershipDoc_file_source',


    FN_SM_PAN: 'Firm Pan',
    FN_SM_AADHAR: 'Firm Aadhar',
    FN_SM_AFFADAVAIT: 'Firm Affadavait',
    FN_SM_CHARAC_CERT: 'Firm Character Certificate',

    SRC_SM_PAN: 'firmcompany_pan_file_source',
    SRC_SM_AADHAR: 'firmcompany_aadhar_file_source',
    SRC_SM_AFFADAVAIT: 'firmcompany_affadavait_file_source',
    SRC_SM_CHARAC_CERT: 'firmcompany_character_file_source',

    FN_SITE_PHOTO: 'Site Photo',
    SRC_SITE_PHOTO: 'site_photo_file_source',


    /**
     * License category and subcategory for WHOLESALE
     */
    WHOLESALE_LICENSE_CATEGORY: 'WHOLESALE',
    WHOLESALE_LICENSE_CATEGORY_DESC: 'Wholesale CSD',
    WHOLESALE_FL2_SUBCATEGORY: 'FL2',
    WHOLESALE_FL2_SUBCATEGORY_DESC: 'FL-2',
    WHOLESALE_FL2A_SUBCATEGORY: 'FL2A',
    WHOLESALE_FL2A_SUBCATEGORY_DESC: 'FL-2A',
    WHOLESALE_FL2B_SUBCATEGORY: 'FL2B',
    WHOLESALE_FL2B_SUBCATEGORY_DESC: 'FL-2B',
    WHOLESALE_CL2_SUBCATEGORY: 'CL2',
    WHOLESALE_CL2_SUBCATEGORY_DESC: 'CL-2',
    WHOLESALE_ID3_SUBCATEGORY: 'ID3',
    WHOLESALE_ID3_SUBCATEGORY_DESC: 'ID-3',

    /**
     * License category and subcategory for EVENT_BAR
     */
    EVENT_BAR_LICENSE_CATEGORY: 'EVENT_BAR',
    EVENT_BAR_LICENSE_CATEGORY_DESC: 'Event Bar',
    EVENT_BAR_FL11_SUBCATEGORY: 'FL11',
    EVENT_BAR_FL11_SUBCATEGORY_DESC: 'FL-11',

    /**
     * License category and subcategory for HBR
     */
    HBR_LICENSE_CATEGORY: 'HBR',
    HBR_LICENSE_CATEGORY_DESC: 'HBR',
    HBR_FL6_SUBCATEGORY: 'FL6',
    HBR_FL6_SUBCATEGORY_DESC: 'FL-6',
    HBR_FL7_SUBCATEGORY: 'FL7',
    HBR_FL7_SUBCATEGORY_DESC: 'FL-7',
    HBR_FL7A_SUBCATEGORY: 'FL7A',
    HBR_FL7A_SUBCATEGORY_DESC: 'FL-7A',
    HBR_FL8_SUBCATEGORY: 'FL8',
    HBR_FL8_SUBCATEGORY_DESC: 'FL-8',
    HBR_FLAL1_SUBCATEGORY: 'FLAL1',
    HBR_FLAL1_SUBCATEGORY_DESC: 'FLAL-1',

    /**
     * License category and subcategory for BWFL Parent Unit
     */
    BWFL_PARENT_LICENSE_CATEGORY: 'BWFL',
    BWFL_PARENT_LICENSE_CATEGORY_DESC: 'BWFL Parent',
    BWFL_PARENT_LICENSE_SUBCATEGORY: 'BWFL',
    BWFL_PARENT_LICENSE_SUBCATEGORY_DESC: 'BWFL',

    /**
     * License category and subcategory for BOND_WAREHOUSE
     */
    BOND_WAREHOUSE_LICENSE_CATEGORY: 'WAREHOUSE',
    BOND_WAREHOUSE_LICENSE_CATEGORY_DESC: 'WareHouse License BWFL',
    BOND_WAREHOUSE_2A_SUBCATEGORY: 'BWFL_2A',
    BOND_WAREHOUSE_2A_SUBCATEGORY_DESC: 'BWFL-2A',
    BOND_WAREHOUSE_2B_SUBCATEGORY: 'BWFL_2B',
    BOND_WAREHOUSE_2B_SUBCATEGORY_DESC: 'BWFL-2B',
    BOND_WAREHOUSE_2C_SUBCATEGORY: 'BWFL_2C',
    BOND_WAREHOUSE_2C_SUBCATEGORY_DESC: 'BWFL-2C',
    BOND_WAREHOUSE_2D_SUBCATEGORY: 'BWFL_2D',
    BOND_WAREHOUSE_2D_SUBCATEGORY_DESC: 'BWFL-2D',

    /**
     * License category and subcategory for DISTILLERY
     */
    DISTI_BOTTL_LICENSE_CATEGORY: 'DISTILLERY',
    DISTI_BOTTL_LICENSE_CATEGORY_DESC: 'Distillery Bottling',
    DISTI_BOTTL_CLB1_SUBCATEGORY: 'CLB1',
    DISTI_BOTTL_CLB1_SUBCATEGORY_DESC: 'CL-B1',
    DISTI_BOTTL_CLB2_SUBCATEGORY: 'CLB2',
    DISTI_BOTTL_CLB2_SUBCATEGORY_DESC: 'CL-B2',
    DISTI_BOTTL_DS1_SUBCATEGORY: 'DS1',
    DISTI_BOTTL_DS1_SUBCATEGORY_DESC: 'DS-1',
    DISTI_BOTTL_FL1_SUBCATEGORY: 'FL1',
    DISTI_BOTTL_FL1_SUBCATEGORY_DESC: 'FL-1',
    DISTI_BOTTL_FL1A_SUBCATEGORY: 'FL1A',
    DISTI_BOTTL_FL1A_SUBCATEGORY_DESC: 'FL-1A',
    DISTI_BOTTL_FL3_SUBCATEGORY: 'FL3',
    DISTI_BOTTL_FL3_SUBCATEGORY_DESC: 'FL-3',
    DISTI_BOTTL_FL3A_SUBCATEGORY: 'FL3A',
    DISTI_BOTTL_FL3A_SUBCATEGORY_DESC: 'FL-3A',
    DISTI_BOTTL_FL16_SUBCATEGORY: 'FL16',
    DISTI_BOTTL_FL16_SUBCATEGORY_DESC: 'FL-16',
    DISTI_BOTTL_FL17_SUBCATEGORY: 'FL17',
    DISTI_BOTTL_FL17_SUBCATEGORY_DESC: 'FL-17',
    DISTI_BOTTL_FL32_SUBCATEGORY: 'FL32',
    DISTI_BOTTL_FL32_SUBCATEGORY_DESC: 'FL-32',
    DISTI_BOTTL_FL39_SUBCATEGORY: 'FL39',
    DISTI_BOTTL_FL39_SUBCATEGORY_DESC: 'FL-39',
    DISTI_BOTTL_FL40_SUBCATEGORY: 'FL40',
    DISTI_BOTTL_FL40_SUBCATEGORY_DESC: 'FL-40',
    DISTI_BOTTL_FL41_SUBCATEGORY: 'FL41',
    DISTI_BOTTL_FL41_SUBCATEGORY_DESC: 'FL-41',
    DISTI_BOTTL_FL49_SUBCATEGORY: 'FL49',
    DISTI_BOTTL_FL49_SUBCATEGORY_DESC: 'FL-49',
    DISTI_BOTTL_PD1_SUBCATEGORY: 'PD1',
    DISTI_BOTTL_PD1_SUBCATEGORY_DESC: 'PD-1',
    DISTI_BOTTL_PD2_SUBCATEGORY: 'PD2',
    DISTI_BOTTL_PD2_SUBCATEGORY_DESC: 'PD-2',
    DISTI_BOTTL_PD32_SUBCATEGORY: 'PD32',
    DISTI_BOTTL_PD32_SUBCATEGORY_DESC: 'PD-32',
    DISTI_BOTTL_PD33_SUBCATEGORY: 'PD33',
    DISTI_BOTTL_PD33_SUBCATEGORY_DESC: 'PD-33',
    DISTI_BOTTL_PD34_SUBCATEGORY: 'PD34',
    DISTI_BOTTL_PD34_SUBCATEGORY_DESC: 'PD-34',


    /**
     * Workflow api call module and sub module codes are here
     */
    MODULE_NAME_CODE: 'LICENSE_MANAGEMENT',

    // For WHOLESALE
    WHOLESALE_FL2_WORKFLOW_NAME: 'WHOLESALE_FL2',
    WHOLESALE_FL2A_WORKFLOW_NAME: 'WHOLESALE_FL2A',
    WHOLESALE_FL2B_WORKFLOW_NAME: 'WHOLESALE_FL2B',
    WHOLESALE_CL2_WORKFLOW_NAME: 'WHOLESALE_CL2',
    WHOLESALE_ID3_WORKFLOW_NAME: 'WHOLESALE_ID3',

    // For EVENT_BAR
    EVENT_BAR_FL11_WORKFLOW_NAME: 'EVENT_BAR_FL11',

    // For HBR
    HBR_FL6_WORKFLOW_NAME: 'HBR_FL6',
    HBR_FL7_WORKFLOW_NAME: 'HBR_FL7',
    HBR_FL7A_WORKFLOW_NAME: 'HBR_FL7A',
    HBR_FL8_WORKFLOW_NAME: 'HBR_FL8',
    HBR_FLAL1_WORKFLOW_NAME: 'HBR_FLAL1',

    // For BWFL Parent
    BWFL_PARENT_UNIT_WORKFLOW_NAME: 'LICENSE_BWFL_PARENT_UNIT',

    // For BOND_WAREHOUSE
    BOND_WAREHOUSE_2A_WORKFLOW_NAME: 'BWFL_2A',
    BOND_WAREHOUSE_2B_WORKFLOW_NAME: 'BWFL_2B',
    BOND_WAREHOUSE_2C_WORKFLOW_NAME: 'BWFL_2C',
    BOND_WAREHOUSE_2D_WORKFLOW_NAME: 'BWFL_2D',

    // For DISTILLERY
    DISTI_BOTTL_CL_B1_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_CLB1',
    DISTI_BOTTL_CL_B2_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_CLB2',
    DISTI_BOTTL_DS_1_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_DS1',
    DISTI_BOTTL_FL_1_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL1',
    DISTI_BOTTL_FL_1A_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL1A',
    DISTI_BOTTL_FL_3_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL3',
    DISTI_BOTTL_FL_3A_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL3A',
    DISTI_BOTTL_FL_16_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL16',
    DISTI_BOTTL_FL_17_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL17',
    DISTI_BOTTL_FL_32_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL32',
    DISTI_BOTTL_FL_39_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL39',
    DISTI_BOTTL_FL_40_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL40',
    DISTI_BOTTL_FL_41_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL41',
    DISTI_BOTTL_FL_49_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_FL49',
    DISTI_BOTTL_PD_1_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_PD1',
    DISTI_BOTTL_PD_2_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_PD2',
    DISTI_BOTTL_PD_32_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_PD32',
    DISTI_BOTTL_PD_33_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_PD33',
    DISTI_BOTTL_PD_34_WORKFLOW_NAME: 'DISTILLERY_BOTTLING_PD34',

    /**
     * application code for all modules listed here
     */
    APPLI_CODE_WHOLESALE: 'WL',
    APPLI_CODE_EVENT_BAR: 'EBL',
    APPLI_CODE_HBR: 'HBRL',
    APPLI_CODE_BWFL: 'BWFL',
    APPLI_CODE_BONDWAREHOUSE: 'BWHL',
    APPLI_CODE_DISTILLERY: 'DL',

    SCREEN_NAME_MODULE: 'licence-mangement',
    SCREEN_NAME_WHOLESALE: 'whole-sale',
    SCREEN_NAME_EVENT_BAR: 'Event-bar',
    SCREEN_NAME_HBR: 'hbr',
    SCREEN_NAME_BWFL: 'bwfl-parent-unit',
    SCREEN_NAME_BONDWAREHOUSE: 'bond-warehouse',
    SCREEN_NAME_DISTILLERY: 'distillery-bottling',

    LICENSE_URL: {
        VIEW_LICENSE_STATUS: '/licencemgnt/viewLicenseStatus/',
        ACKNOWLEDGEMENT: '/licencemgnt/acknowledgement/',
        PAYMENT: '/licencemgnt/payment/',
        SUGAR_MILL: '/licencemgnt/sugarmill-license/',
        RETAIL: '/licencemgnt/retail/',
        WHOLESALE: '/licencemgnt/wholesale/',
        EVENT_BAR: '/licencemgnt/eventbarlicense/',
        DISTILLERY: '/licencemgnt/distillery-bottling/',
        HBR: '/licencemgnt/hbr/',
        BWFL: '/licencemgnt/bwflparentunit/',
        WAREHOUSE: '/licencemgnt/bondwarehouse/',
    },

    docuPropObj: {
        applicantDetails: 'applicantDocumentList',
        addressList: 'addressDocumentList',
        bankList: 'bankDocumentList',
        businessUnitDetails: 'businessUnitDocumentList',

        // for WHOLESALE
        wholeSaleAdditionalDetails: 'additionalDocumentList',

        // for HBR
        hbrAuthorizePerson: 'authorizePersonDocumentList',
        hbrSeftAttestation: 'attestationDocumentList',
        hbrAdditionalDetails: 'additionalDocumentList',
        hbrPremisesDetails: 'premisesDocumentList',
        hbrFirmCompanyDetailList: 'firmCompanyDocumentList',

        // for DISTILLERY
        distilleryAdditionalDetails: 'additionalDocumentList',
    }

};

export const SubCategoryDescConstants = {
    WHOLESALE: {
        [LicenseConstants.WHOLESALE_FL2_SUBCATEGORY]: LicenseConstants.WHOLESALE_FL2_SUBCATEGORY_DESC,
        [LicenseConstants.WHOLESALE_FL2A_SUBCATEGORY]: LicenseConstants.WHOLESALE_FL2A_SUBCATEGORY_DESC,
        [LicenseConstants.WHOLESALE_FL2B_SUBCATEGORY]: LicenseConstants.WHOLESALE_FL2B_SUBCATEGORY_DESC,
        [LicenseConstants.WHOLESALE_CL2_SUBCATEGORY]: LicenseConstants.WHOLESALE_CL2_SUBCATEGORY_DESC,
        [LicenseConstants.WHOLESALE_ID3_SUBCATEGORY]: LicenseConstants.WHOLESALE_ID3_SUBCATEGORY_DESC,
    },
    HBR: {
        [LicenseConstants.HBR_FL6_SUBCATEGORY]: LicenseConstants.HBR_FL6_SUBCATEGORY_DESC,
        [LicenseConstants.HBR_FL7_SUBCATEGORY]: LicenseConstants.HBR_FL7_SUBCATEGORY_DESC,
        [LicenseConstants.HBR_FL7A_SUBCATEGORY]: LicenseConstants.HBR_FL7A_SUBCATEGORY_DESC,
        [LicenseConstants.HBR_FL8_SUBCATEGORY]: LicenseConstants.HBR_FL8_SUBCATEGORY_DESC,
        [LicenseConstants.HBR_FLAL1_SUBCATEGORY]: LicenseConstants.HBR_FLAL1_SUBCATEGORY_DESC,
    },
    BWFL: {
        [LicenseConstants.BWFL_PARENT_LICENSE_SUBCATEGORY]: LicenseConstants.BWFL_PARENT_LICENSE_SUBCATEGORY_DESC
    },
    WAREHOUSE: {
        [LicenseConstants.BOND_WAREHOUSE_2A_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2A_SUBCATEGORY_DESC,
        [LicenseConstants.BOND_WAREHOUSE_2B_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2B_SUBCATEGORY_DESC,
        [LicenseConstants.BOND_WAREHOUSE_2C_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2C_SUBCATEGORY_DESC,
        [LicenseConstants.BOND_WAREHOUSE_2D_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2D_SUBCATEGORY_DESC,
    },
    DISTILLERY: {
        [LicenseConstants.DISTI_BOTTL_CLB1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_CLB1_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_CLB2_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_CLB2_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_DS1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_DS1_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL1_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL1A_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL1A_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL3_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL3_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL3A_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL3A_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL16_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL16_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL17_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL17_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL32_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL32_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL39_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL39_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL40_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL40_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL41_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL41_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_FL49_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL49_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_PD1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD1_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_PD2_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD2_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_PD32_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD32_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_PD33_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD33_SUBCATEGORY_DESC,
        [LicenseConstants.DISTI_BOTTL_PD34_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD34_SUBCATEGORY_DESC
    },
};

export const WorkFlowNameListConstants = {
    WHOLESALE: {
        [LicenseConstants.WHOLESALE_FL2_SUBCATEGORY]: LicenseConstants.WHOLESALE_FL2_WORKFLOW_NAME,
        [LicenseConstants.WHOLESALE_FL2A_SUBCATEGORY]: LicenseConstants.WHOLESALE_FL2A_WORKFLOW_NAME,
        [LicenseConstants.WHOLESALE_FL2B_SUBCATEGORY]: LicenseConstants.WHOLESALE_FL2B_WORKFLOW_NAME,
        [LicenseConstants.WHOLESALE_CL2_SUBCATEGORY]: LicenseConstants.WHOLESALE_CL2_WORKFLOW_NAME,
        [LicenseConstants.WHOLESALE_ID3_SUBCATEGORY]: LicenseConstants.WHOLESALE_ID3_WORKFLOW_NAME,
    },
    HBR: {
        [LicenseConstants.HBR_FL6_SUBCATEGORY]: LicenseConstants.HBR_FL6_WORKFLOW_NAME,
        [LicenseConstants.HBR_FL7_SUBCATEGORY]: LicenseConstants.HBR_FL7_WORKFLOW_NAME,
        [LicenseConstants.HBR_FL7A_SUBCATEGORY]: LicenseConstants.HBR_FL7A_WORKFLOW_NAME,
        [LicenseConstants.HBR_FL8_SUBCATEGORY]: LicenseConstants.HBR_FL8_WORKFLOW_NAME,
        [LicenseConstants.HBR_FLAL1_SUBCATEGORY]: LicenseConstants.HBR_FLAL1_WORKFLOW_NAME,
    },
    EVENT_BAR: {
        [LicenseConstants.EVENT_BAR_FL11_SUBCATEGORY]: LicenseConstants.EVENT_BAR_FL11_WORKFLOW_NAME
    },
    BWFL: {
        [LicenseConstants.BWFL_PARENT_LICENSE_SUBCATEGORY]: LicenseConstants.BWFL_PARENT_UNIT_WORKFLOW_NAME
    },
    WAREHOUSE: {
        [LicenseConstants.BOND_WAREHOUSE_2A_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2A_WORKFLOW_NAME,
        [LicenseConstants.BOND_WAREHOUSE_2B_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2B_WORKFLOW_NAME,
        [LicenseConstants.BOND_WAREHOUSE_2C_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2C_WORKFLOW_NAME,
        [LicenseConstants.BOND_WAREHOUSE_2D_SUBCATEGORY]: LicenseConstants.BOND_WAREHOUSE_2D_WORKFLOW_NAME,
    },
    DISTILLERY: {
        [LicenseConstants.DISTI_BOTTL_CLB1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_CL_B1_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_CLB2_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_CL_B2_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_DS1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_DS_1_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_1_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL1A_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_1A_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL3_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_3_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL3A_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_3A_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL16_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_16_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL17_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_17_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL32_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_32_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL39_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_39_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL40_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_40_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL41_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_41_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_FL49_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_FL_49_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_PD1_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD_1_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_PD2_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD_2_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_PD32_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD_32_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_PD33_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD_33_WORKFLOW_NAME,
        [LicenseConstants.DISTI_BOTTL_PD34_SUBCATEGORY]: LicenseConstants.DISTI_BOTTL_PD_34_WORKFLOW_NAME
    },
};

export const CheckListCodeConstants = {
    WHOLESALE: {
        [LicenseConstants.WHOLESALE_FL2_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_FL2,
        [LicenseConstants.WHOLESALE_FL2A_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_FL2A,
        [LicenseConstants.WHOLESALE_FL2B_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_FL2B,
        [LicenseConstants.WHOLESALE_CL2_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_CL2,
        [LicenseConstants.WHOLESALE_ID3_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_ID3,
    },
    HBR: {
        [LicenseConstants.HBR_FL6_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_FL2,
        [LicenseConstants.HBR_FL7_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_FL2A,
        [LicenseConstants.HBR_FL7A_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_FL2B,
        [LicenseConstants.HBR_FL8_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_CL2,
        [LicenseConstants.HBR_FLAL1_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_WHOLESALE_ID3,
    },
    EVENT_BAR: {
        [LicenseConstants.EVENT_BAR_FL11_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_EVENT_BAR_FL11
    },
    BWFL: {
        [LicenseConstants.BWFL_PARENT_LICENSE_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_BWFL_PARENT_UNIT
    },
    WAREHOUSE: {
        [LicenseConstants.BOND_WAREHOUSE_2A_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_BOND_WAREHOUSE_2A,
        [LicenseConstants.BOND_WAREHOUSE_2B_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_BOND_WAREHOUSE_2B,
        [LicenseConstants.BOND_WAREHOUSE_2C_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_BOND_WAREHOUSE_2C,
        [LicenseConstants.BOND_WAREHOUSE_2D_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_BOND_WAREHOUSE_2D,
    },
    DISTILLERY: {
        [LicenseConstants.DISTI_BOTTL_CLB1_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_CL_B1,
        [LicenseConstants.DISTI_BOTTL_CLB2_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_CL_B2,
        [LicenseConstants.DISTI_BOTTL_DS1_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_DS_1,
        [LicenseConstants.DISTI_BOTTL_FL1_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_1,
        [LicenseConstants.DISTI_BOTTL_FL1A_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_1A,
        [LicenseConstants.DISTI_BOTTL_FL3_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_3,
        [LicenseConstants.DISTI_BOTTL_FL3A_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_3A,
        [LicenseConstants.DISTI_BOTTL_FL16_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_16,
        [LicenseConstants.DISTI_BOTTL_FL17_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_17,
        [LicenseConstants.DISTI_BOTTL_FL32_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_32,
        [LicenseConstants.DISTI_BOTTL_FL39_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_39,
        [LicenseConstants.DISTI_BOTTL_FL40_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_40,
        [LicenseConstants.DISTI_BOTTL_FL41_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_41,
        [LicenseConstants.DISTI_BOTTL_FL49_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_FL_49,
        [LicenseConstants.DISTI_BOTTL_PD1_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_PD_1,
        [LicenseConstants.DISTI_BOTTL_PD2_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_PD_2,
        [LicenseConstants.DISTI_BOTTL_PD32_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_PD_32,
        [LicenseConstants.DISTI_BOTTL_PD33_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_PD_33,
        [LicenseConstants.DISTI_BOTTL_PD34_SUBCATEGORY]: LicenseConstants.CODE_CHECKLIST_DISTI_BOTTL_PD_34
    },
};

