export const environment = {
  name: 'uat',
  production: true,
  authToken: '9184730b-a782-3d57-9ff1-a506d1e3e587',
  tokenURL: 'https://devapigateway.upexciseonline.co/token',
  consumerKey: '3wTWY820rfcxpcfM0W9_rFiDMXIa',
  consumerSecret: 'PNnRmNk6TtsUG8kkZe5zAaZWMAMa',
  tokenUsername: 'admin',
  tokenPassword: 'Adm9jsd32',
  baseURLMaster: 'https://uatapigateway.upexciseonline.co/master/v1.0.0/',
  baseURL: 'https://uatapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  jsonBaseURL: 'https://json.upexciseonline.co/',
  baseURLUser: 'https://uatapigateway.upexciseonline.co/user-managment/v1.0.0/',
  sugarmillBaseURL: 'https://uatapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  distilleryBaseURL: 'https://uatapigateway.upexciseonline.co/distillery/v1.0.0/',
  localDBUrl: 'https://json.upexciseonline.co/',
  // licencemanagementURL: 'http://65.0.150.210:3505/licenseManagement/',
  licencemanagementURL: 'https://devapigateway.upexciseonline.co/licensemanagementnew/v1.0.0/',
  wholesaleURL: 'http://65.0.150.210:3509/',
  warehouseURL: 'https://devapigateway.upexciseonline.co/warehouse/1.0.0/',
  baseURLRetail: 'https://uatapigateway.upexciseonline.co/retailpos/v1.0.0/',
  workflowconfig:'https://uatapigateway.upexciseonline.co/workflow/v1.0.0/',
  documentUrl: 'https://devapigateway.upexciseonline.co/docManagement/v1.0.0/',
  licencemanagementIPURL: 'http://65.0.150.210:3505/licenseManagement/',
  parentunit: 'https://devapigateway.upexciseonline.co/parentUnit/1.0/',
  warehouseurl: 'https://devapigateway.upexciseonline.co/warehouse/1.0.0/',
  helpdesk:'http://65.0.150.210:3506/helpdesk/',
};
