export const environment = {
  production: true,
  authToken: '9184730b-a782-3d57-9ff1-a506d1e3e587',
  baseURLMaster: 'https://uatapigateway.upexciseonline.co/master/v1.0.0/',
  baseURL: 'https://uatapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  jsonBaseURL: 'https://json.upexciseonline.co/',
  baseURLUser: 'https://uatapigateway.upexciseonline.co/user-managment/v1.0.0/',
  sugarmillBaseURL: 'https://uatapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  distilleryBaseURL: 'https://uatapigateway.upexciseonline.co/distillery/v1.0.0/',
  localDBUrl: 'https://json.upexciseonline.co/',
  // licencemanagementURL: 'http://65.0.150.210:3505/licenseManagement/',
  licencemanagementURL: 'https://devapigateway.upexciseonline.co/licensemanagementnew/v1.0.0/',
  tokenURL: 'https://devapigateway.upexciseonline.co/token',
  warehouseURL: "https://devapigateway.upexciseonline.co/warehouse/1.0.0/",
  warehouseurl: 'https://devapigateway.upexciseonline.co/warehouse/1.0.0/',
  consumerKey: '123456',
  helpdeskURL: 'http://65.0.150.210:3506/',
  tokenUsername: 'admin',
  tokenPassword: 'Adm9jsd32',
  workflowconfig: "https://devapigateway.upexciseonline.co/workflow/v1.0.0",
  parentunit: 'https://devapigateway.upexciseonline.co/parentUnit/1.0/',
  helpdesk:'http://65.0.150.210:3506/helpdesk/',
};
