export const environment = {
  name: 'dev',
  production: true,
  authToken: '24d14de9-8237-3ff9-805a-c212281d6e90',
  tokenURL: 'https://devapigateway.upexciseonline.co/token/',
  consumerKey: 'wm8ZarwKn2UZ8tZQpqDCarzXUnwa',
  consumerSecret: 'v4AOZnFxUH492bG9TOHOnuqRZOAa',
  tokenUsername: 'admin',
  tokenPassword: 'Adm9jsd32',
  baseURLMaster: 'https://devapigateway.upexciseonline.co/master/v1.0.0/',
  baseURL: 'https://devapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  jsonBaseURL: 'https://json.upexciseonline.co/',
  baseURLUser: 'https://devapigateway.upexciseonline.co/user-managment/v1.0.0/',
  sugarmillBaseURL: 'https://devapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  distilleryBaseURL: 'https://devapigateway.upexciseonline.co/distillery/v1.0.0/',
  localDBUrl: 'https://json.upexciseonline.co/',
  // licencemanagementURL: 'http://65.0.150.210:3505/licenseManagement/',
  licencemanagementURL: 'https://devapigateway.upexciseonline.co/licensemanagement/v1.0.0/',
  wholesaleURL: 'https://devapigateway.upexciseonline.co/wholesale/1.0.0/',
  warehouseURL: 'https://devapigateway.upexciseonline.co/warehouse/1.0.0/',
  warehouseurl: 'https://devapigateway.upexciseonline.co/warehouse/1.0.0/',
  helpdeskURL: 'https://devapigateway.upexciseonline.co/helpdesk/v1.0.0/',
  indentrequsetURL: 'https://devapigateway.upexciseonline.co/v1.0.0/',
  baseURLRetail: 'https://devapigateway.upexciseonline.co/retailpos/v1.0.0/',
  workflowconfig: 'https://devapigateway.upexciseonline.co/workflow/v1.0.0/',
  // adding  new apis
  //devisionUrl: 'https://devapigateway.upexciseonline.co/masterData/v1.0.0/',
  devisionUrl: 'https://devapigateway.upexciseonline.co/master/v1.0.0/',
  documentIPUrl: 'https://devapigateway.upexciseonline.co/docManagement/v1.0.0/',
  documentUrl: 'https://devapigateway.upexciseonline.co/docManagement/v1.0.0/',
  licencemanagementIPURL: 'https://devapigateway.upexciseonline.co/licensemanagement/v1.0.0/',
  wholesaledevURL: 'https://devapigateway.upexciseonline.co/wholesale/1.0.0/',
  userManagerUrl: 'https://devapigateway.upexciseonline.co/user-managment/v1.0.0/',
  worflowIPURL: 'https://devapigateway.upexciseonline.co/workflow/v1.0.0/',
  parentunit: 'https://devapigateway.upexciseonline.co/parentUnit/1.0/',
  parentUnit: 'https://devapigateway.upexciseonline.co/parentUnit/1.0/',
  // warehouseurl: 'http://65.0.150.210:3508/warehouse/',
  notificationURL: 'https://devapigateway.upexciseonline.co/notification/v1.0.0/',
  helpdesk:'http://65.0.150.210:3506/helpdesk/',
  wareHouse: "http://65.0.150.210:3508/warehouse/",
};
